name: rebase-dependabot-pr
on:
  push:
    branches: [ main ]
jobs:
  rebase-dependabot-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Set up secrets
        run: echo '${{ secrets.GITHUB_TOKEN }}' > ~/.config/github-token

      - name: Checkout bots repo
        uses: actions/checkout@v4
        with:
          repository: cockpit-project/bots
          ref: dependabot-recreate

      - name: Run dependabot-recreate-pr
        run: |
          GITHUB_BASE=${GITHUB_REPOSITORY} ./dependabot-recreate-pr
